[gait-selection-develop] Feature: subgait transitions
project-march/march pull request #581
Opened 2020-08-24 07:50 UTC by Olavhaasie

Closes PM-543

## Description
This PR adds the final feature to the new gait selection: Transition gaits :tada: The only small thing that is missing is that you can start the walk gait from a small or large size (PM-554)

I have implemented the transitions on subgait level and are therefore included in the gait graph.

## Changes
* Add increase and decrease size transitions in state machine
* Implement transitioning on `SetpointsGait`
* Remove `GaitSelection` dependency on `TransitionSubgait` and create from subgait objects instead
* Added forgotten timestamp to published messages

## Testing
Checkout `gait-selection-develop` on gait-files, monitor and simulation. Run the simulation and make sure you use `gait_directory:=minimal`. Then start walking and transitioning between sizes.

2020-08-24 11:45 UTC, Roelemans requested changes
![image](https://user-images.githubusercontent.com/47626418/91031278-a58b9c00-e600-11ea-848b-1c82f83f7db9.png)
When you click "increase step size" during a transition, the simulation crashes :crying_cat_face: .

2020-08-24 11:45 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/state_machine/setpoints_gait.py
> +            name = self.graph[(self._current_subgait.subgait_name, self.graph.DECREASE_SIZE)]
Feels a bit strange to basically use two different Enums here, but not sure if there is a better way

2020-08-24 11:55 UTC, Olavhaasie commented on march_gait_selection/src/march_gait_selection/state_machine/setpoints_gait.py
> +            elif self._should_stop:
The first one I can easily solve indeed. The second one is a lot harder to execute, I could create an issue for the next team :innocent:

2020-08-24 11:57 UTC, Olavhaasie commented on march_gait_selection/src/march_gait_selection/state_machine/setpoints_gait.py
> +            name = self.graph[(self._current_subgait.subgait_name, self.graph.DECREASE_SIZE)]
Yes I agree, it does not look natural. However, these represent two different things. The `TransitionRequest` is an actual enum with different values, whereas the `graph.DECREASE_SIZE` just a string value is for the name of the transition.

2020-08-24 12:28 UTC, Olavhaasie commented
> When you click "increase step size" during a transition, the simulation crashes crying_cat_face .

Thanks for your review and for finding the crashes. I fixed it so that you can not execute stop or transition during the other.

2020-08-24 12:53 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/state_machine/setpoints_gait.py
> +            elif self._should_stop:
Lekker :ostrich: :stuck_out_tongue:

2020-08-24 13:35 UTC, Roelemans requested changes
Good job fixing the errors! One last thing: when pressing stop during a transition now, the stop now gets rejected instead of postponed until after the transition. This is arguably worse since you would prefer the stop to happen as quickly as possible even if you can't do it immediately. However, you can also just postpone this to the other issue :innocent: 
![image](https://user-images.githubusercontent.com/47626418/91050503-0a55ef00-e61f-11ea-9519-5b128746d38f.png)

2020-08-24 13:36 UTC, Olavhaasie commented
> However, you can also just postpone this to the other issue

That's exactly what I was thinking :stuck_out_tongue_winking_eye:

2020-08-24 13:37 UTC, Roelemans approved these changes

2020-08-25 10:47 UTC, JorisWeeda requested changes
I get an error when building with your testing settings;
`
--- stderr: march_gait_files
CMake Error at cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/home/joris/march_ws/src/gait-files/march_gait_files/airgait".
`
Looking at your cmake file u state that there is an _airgait_ folder but this does not exist. Not sure why Roel did not encounter this problem tho.

2020-08-25 10:53 UTC, Olavhaasie commented
> I get an error when building with your testing settings;
> `--- stderr: march_gait_files CMake Error at cmake_install.cmake:56 (file): file INSTALL cannot find "/home/joris/march_ws/src/gait-files/march_gait_files/airgait".`
> Looking at your cmake file u state that there is an _airgait_ folder but this does not exist. Not sure why Roel did not encounter this problem tho.

Oopsie, I fixed it. I did this after Roel's review

2020-08-25 11:13 UTC, JorisWeeda approved these changes
Looks nice, except for the _stop_ problem as roel described everything looks fine by me. nice work! :fire:

2020-08-25 11:52 UTC, merged